export const SAVE_PATIENT_REQUEST = "SAVE_PATIENT_REQUEST";
export const FETCH_PATIENT_REQUEST = "FETCH_PATIENT_REQUEST";
export const UPDATE_PATIENT_REQUEST = "UPDATE_PATIENT_REQUEST";
export const DELETE_PATIENT_REQUEST = "DELETE_PATIENT_REQUEST";
export const PATIENT_SUCCESS = "PATIENT_SUCCESS";
export const PATIENT_FAILURE = "PATIENT_FAILURE";

export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST";
export const CENTERS_SUCCESS = "CENTERS_SUCCESS";
export const CENTERS_FAILURE = "CENTERS_FAILURE";

export const FETCH_GENDERS_REQUEST = "FETCH_GENDERS_REQUEST";
export const GENDERS_SUCCESS = "GENDERS_SUCCESS";
export const GENDERS_FAILURE = "GENDERS_FAILURE";

//added for bg
export const FETCH_BGS_REQUEST = "FETCH_BGS_REQUEST";
export const BGS_SUCCESS = "BGS_SUCCESS";
export const BGS_FAILURE = "BGS_FAILURE";
//

//added for organ 

export const FETCH_ORGANS_REQUEST = "FETCH_ORGANS_REQUEST";
export const ORGANS_SUCCESS = "ORGANS_SUCCESS";
export const ORGANS_FAILURE = "ORGANS_FAILURE";
//