export const SAVE_DONAR_REQUEST = "SAVE_DONAR_REQUEST";
export const FETCH_DONAR_REQUEST = "FETCH_DONAR_REQUEST";
export const UPDATE_DONAR_REQUEST = "UPDATE_DONAR_REQUEST";
export const DELETE_DONAR_REQUEST = "DELETE_DONAR_REQUEST";
export const DONAR_SUCCESS = "DONAR_SUCCESS";
export const DONAR_FAILURE = "DONAR_FAILURE";

export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST";
export const CENTERS_SUCCESS = "CENTERS_SUCCESS";
export const CENTERS_FAILURE = "CENTERS_FAILURE";

//added for bg
export const FETCH_BGS_REQUEST = "FETCH_BGS_REQUEST";
export const BGS_SUCCESS = "BGS_SUCCESS";
export const BGS_FAILURE = "BGS_FAILURE";
//

export const FETCH_GENDERS_REQUEST = "FETCH_GENDERS_REQUEST";
export const GENDERS_SUCCESS = "GENDERS_SUCCESS";
export const GENDERS_FAILURE = "GENDERS_FAILURE";

//added for organ 

export const FETCH_ORGANS_REQUEST = "FETCH_ORGANS_REQUEST";
export const ORGANS_SUCCESS = "ORGANS_SUCCESS";
export const ORGANS_FAILURE = "ORGANS_FAILURE";
//