export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SAVED_SUCCESS = "USER_SAVED_SUCCESS";


export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const ROLES_REQUEST = "ROLES_REQUEST";
export const ROLES_SUCCESS = "ROLES_SUCCESS";
export const ROLES_FAILURE = "ROLES_FAILURE";
